<section class="relative min-h-screen flex items-center overflow-hidden pt-16 hero-gradient"><!-- Decorative background elements --><div class="absolute inset-0 z-0"><!-- Floating paint elements --><div class="absolute top-20 left-10 w-80 h-40 bg-clay opacity-15 transform rotate-12 rounded-full floating">
            </div><div class="absolute bottom-40 right-20 w-64 h-32 bg-deep-teal opacity-10 transform -rotate-6 rounded-full floating" id="i1rnyh"></div><div class="absolute top-1/3 left-1/4 w-64 h-64 bg-ochre opacity-10 floating" id="iqsdiv">
            </div><div class="absolute top-1/2 right-1/3 w-32 h-32 bg-crimson opacity-10 rounded-full floating" id="ix2ead"></div><!-- Pattern overlay --><div class="absolute inset-0 opacity-10" id="ipsn1i">
            </div><!-- Paint splatters --><div class="absolute top-1/4 right-1/5 w-24 h-24 bg-ochre opacity-10 rounded-full" id="iqnmzj"></div><div class="absolute bottom-1/3 left-1/6 w-20 h-20 bg-terracotta opacity-10" id="izm85g"></div></div><div class="container max-w-full mx-10 px-4 py-24 relative z-10"><div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"><div class="max-w-2xl"><div class="mb-8"><span class="inline-block bg-sage text-slate px-4 py-1 rounded-full text-sm font-medium mb-6"><i class="fas fa-star mr-2"></i>Istaknuto ovog meseca
                        </span><h1 class="text-5xl md:text-6xl font-display font-bold leading-tight text-slate mb-6"><span class="block artistic-underline">Mesto gde se umetnost, film i</span><span class="block text-royal-blue mt-2">kultura susreću</span></h1></div><div class="mb-10 relative pl-6 border-l-4 border-ochre"><p class="text-xl text-slate-700 leading-relaxed max-w-lg mb-6">
                            Doživite živopisnu spoju vizuelnih umetnosti, nezavisnog filma, pozorišta i kulturne baštine
                            u našem novom renoviranom prostoru.
                        </p><p class="text-slate-600 italic">
                            "Kulturni centar je srce zajednice, gde različiti izrazi pronalaze zajednički jezik."
                            <span class="block font-medium text-terracotta mt-2">— Elena Rodriguez, Umetnički
                                direktor</span></p></div><!-- Quick links --><div class="mt-10 flex flex-wrap gap-3"><a href="#" title="" target="_self" class="flex items-center text-slate-600 hover:text-terracotta transition-colors"><span class="w-3 h-3 bg-ochre rounded-full mr-2"></span>
                            Trenutne izložbe
                        </a><a href="#" title="" target="_self" class="flex items-center text-slate-600 hover:text-terracotta transition-colors"><span class="w-3 h-3 bg-royal-blue rounded-full mr-2"></span>
                            Raspored filmova
                        </a><a href="#" title="" target="_self" class="flex items-center text-slate-600 hover:text-terracotta transition-colors"><span class="w-3 h-3 bg-velvet rounded-full mr-2"></span>
                            Pozorišne predstave
                        </a><a href="#" title="" target="_self" class="flex items-center text-slate-600 hover:text-terracotta transition-colors"><span class="w-3 h-3 bg-deep-teal rounded-full mr-2"></span>
                            Muzički događaji
                        </a></div></div><!-- Cultural Showcase Grid --><div class="relative"><div class="grid grid-cols-2 gap-6"><!-- Art Exhibition --><div class="artistic-card h-80 rounded-xl overflow-hidden relative"><div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=600&q=80')] bg-cover bg-center transform scale-105 hover:scale-100 transition-transform duration-500">
                            </div><div class="category-badge bg-ochre/80 text-paper">Umetnost</div><div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate/90 to-transparent p-4 text-paper"><h3 class="font-display font-bold">Savremene Perspektive</h3><p class="text-sm">Savremena umetnička izložba</p></div></div><!-- Film --><div class="artistic-card h-80 rounded-xl overflow-hidden relative mt-12"><div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80')] bg-cover bg-center transform scale-105 hover:scale-100 transition-transform duration-500">
                            </div><div class="category-badge bg-royal-blue/80 text-paper">Bioskop</div><div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate/90 to-transparent p-4 text-paper"><h3 class="font-display font-bold">Međunarodni Filmski Festival</h3><p class="text-sm">15-30. jun</p></div></div><!-- Theater --><div class="artistic-card h-64 rounded-xl overflow-hidden relative"><div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80')] bg-cover bg-center transform scale-105 hover:scale-100 transition-transform duration-500">
                            </div><div class="category-badge bg-velvet/80 text-paper">Pozorište</div><div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate/90 to-transparent p-4 text-paper"><h3 class="font-display font-bold">Šekspir u parku</h3><p class="text-sm">Predstave na otvorenom</p></div></div><!-- Music --><div class="artistic-card h-64 rounded-xl overflow-hidden relative -mt-6"><div class="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80')] bg-cover bg-center transform scale-105 hover:scale-100 transition-transform duration-500">
                            </div><div class="category-badge bg-deep-teal/80 text-paper">Muzika</div><div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate/90 to-transparent p-4 text-paper"><h3 class="font-display font-bold">Jazz &amp; Blues Večeri</h3><p class="text-sm">Svakog petka</p></div></div></div></div></div></div><!-- Floating info card --><div class="absolute bottom-20 right-20 z-20 hidden xl:block animate-bounce-slow"><div class="relative"><div class="w-66 h-auto bg-white/90 backdrop-blur-sm p-5 rounded-xl shadow-2xl border-2 border-ochre transform rotate-3"><div class="flex items-center mb-4"><div class="w-14 h-14 bg-sage rounded-full mr-3 flex items-center justify-center text-paper"><i class="fas fa-calendar-alt text-xl"></i></div><div><h4 class="font-display font-bold">Radno vreme</h4><p class="text-terracotta text-sm">Utorak-Nedelja: 10:00-21:00</p></div></div><div class="space-y-2"><div class="flex justify-between text-sm"><span>Opšta:</span><span class="font-medium">1200 RSD</span></div><div class="flex justify-between text-sm"><span>Studenti/Penzioneri:</span><span class="font-medium">800 RSD</span></div><div class="flex justify-between text-sm"><span>Članovi:</span><span class="font-medium">Besplatno</span></div></div></div><div class="absolute -top-6 -right-6 w-12 h-12 bg-sage rounded-full flex items-center justify-center text-paper shadow-lg"><i class="fas fa-ticket-alt"></i></div></div></div><!-- Scrolling indicator --><div class="absolute bottom-10 left-1/2 transform -translate-x-1/2 z-20"><div class="animate-bounce w-8 h-14 rounded-full border-2 border-terracotta flex justify-center p-1"><div class="w-2 h-2 bg-terracotta rounded-full animate-pulse"></div></div></div></section>