<div id="mobileMenu" class="fixed inset-0 z-40 lg:hidden hidden"><div id="mobileMenuOverlay" class="fixed inset-0 bg-black bg-opacity-50"></div><div id="mobileMenuPanel" class="fixed top-0 right-0 h-full w-80 max-w-full bg-paper shadow-xl transform translate-x-full transition-transform duration-300 ease-in-out"><div class="p-6"><div class="flex justify-between items-center mb-8"><h2 class="text-xl text-white font-display font-bold text-slate">Menu</h2><button id="closeMobileMenu" class="text-slate hover:text-terracotta transition-colors"><i class="fas fa-times text-xl"></i></button></div><nav id="navBarIDm" class="space-y-4"><a href="/" title="" target="_self" class="flex items-center py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><i class="fas fa-home mr-3 text-terracotta"></i>Početna
                    </a><div class="mobile-dropdown"><button id="mobileAboutToggle" class="flex items-center justify-between w-full py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><div class="flex items-center"><i class="fas fa-info-circle mr-3 text-ochre"></i>O nama
                            </div><i id="mobileAboutIcon" class="fas fa-chevron-down text-sm transition-transform duration-200"></i></button><div id="mobileAboutMenu" class="ml-6 mt-2 space-y-2 hidden"><a href="/o-nama/cilj" title="" target="_self" class="flex items-center py-2 px-4 text-sm text-slate hover:text-terracotta transition-colors"><i class="fas fa-bullseye mr-2 text-royal-blue"></i>Cilj
                            </a><a href="/o-nama/zaposleni" title="" target="_self" class="flex items-center py-2 px-4 text-sm text-slate hover:text-terracotta transition-colors"><i class="fas fa-sitemap mr-2 text-terracotta"></i>Zaposleni
                            </a><a href="/o-nama/misija" title="" target="_self" class="flex items-center py-2 px-4 text-sm text-slate hover:text-terracotta transition-colors"><i class="fas fa-flag mr-2 text-deep-teal"></i>Misija
                            </a></div></div><a href="/dogadjaji" title="" target="_self" class="flex items-center py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><i class="fas fa-calendar-alt mr-3 text-royal-blue"></i>Dogadjaji
                    </a><a href="/galerija" title="" target="_self" class="flex items-center py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><i class="fas fa-images mr-3 text-velvet"></i>Galerija
                    </a><a href="/dokumenti" title="" target="_self" class="flex items-center py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><i class="fas fa-folder-open mr-3 text-coral"></i>Dokumenti
                    </a><a href="/kontakt" title="" target="_self" class="flex items-center py-3 px-4 text-slate hover:text-terracotta hover:bg-slate-50 rounded-lg transition-all"><i class="fas fa-address-book mr-3 text-deep-teal"></i>Kontakt
                    </a></nav></div></div></div>