SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;	
SET COLLATION_CONNECTION = utf8mb4_unicode_ci;	

INSERT INTO text (source_id, source_table, field_name, lang, content, label)
VALUES
(58, 'document', 'title', 'sr', 'Pravilnik za javne nabavke', 'Pravilnik za javne nabavke - Naslov'),
(58, 'document', 'description', 'sr', 'Akt koji reguliše procedure javnih nabavki.', 'Pravilnik za javne nabavke - Opis'),
(58, 'document', 'title', 'sr-cyrl', 'Правилник за јавне набавке', 'Правилник за јавне набавке - Наслов'),
(58, 'document', 'description', 'sr-cyrl', 'Акт који регулише процедуре јавних набавки.', 'Правилник за јавне набавке - Опис'),
(59, 'document', 'title', 'sr', 'Izveštaj o realizaciji poslovanja za 2024.', 'Izveštaj o poslovanju 2024 - Naslov'),
(59, 'document', 'description', 'sr', 'Godišnji izveštaj o ostvarenom poslovanju za 2024. godinu.', 'Izveštaj o poslovanju 2024 - Opis'),
(59, 'document', 'title', 'sr-cyrl', 'Извештај о реализацији пословања за 2024.', 'Извештај о пословању 2024 - Наслов'),
(59, 'document', 'description', 'sr-cyrl', 'Годишњи извештај о оствареном пословању за 2024. годину.', 'Извештај о пословању 2024 - Опис'),
(60, 'document', 'title', 'sr', 'Pravilnik za javne nabavke (Ažuriran)', 'Pravilnik za javne nabavke - Naslov'),
(60, 'document', 'description', 'sr', 'Akt koji reguliše procedure javnih nabavki.', 'Pravilnik za javne nabavke - Opis'),
(60, 'document', 'title', 'sr-cyrl', 'Правилник за јавне набавке (Ажуриран)', 'Правилник за јавне набавке - Наслов'),
(60, 'document', 'description', 'sr-cyrl', 'Акт који регулише процедуре јавних набавки.', 'Правилник за јавне набавке - Опис'),
(61, 'document', 'title', 'sr', 'Neklasifikovani dokument', 'Neklasifikovani dokument - Naslov'),
(61, 'document', 'description', 'sr', 'Dokument bez definisanog naziva.', 'Neklasifikovani dokument - Opis'),
(61, 'document', 'title', 'sr-cyrl', 'Некласификовани документ', 'Некласификовани документ - Наслов'),
(61, 'document', 'description', 'sr-cyrl', 'Документ без дефинисаног назива.', 'Некласификовани документ - Опис'),
(62, 'document', 'title', 'sr', 'Matični list', 'Matični list - Naslov'),
(62, 'document', 'description', 'sr', 'Obrazac za popunjavanje matičnog lista.', 'Matični list - Opis'),
(62, 'document', 'title', 'sr-cyrl', 'Матични лист', 'Матични лист - Наслов'),
(62, 'document', 'description', 'sr-cyrl', 'Образац за попуњавање матичног листа.', 'Матични лист - Опис'),
(63, 'document', 'title', 'sr', 'Revers za izdavanje arhivske građe', 'Revers za arhivsku građu - Naslov'),
(63, 'document', 'description', 'sr', 'Obrazac reversa za izdavanje arhivske građe.', 'Revers za arhivsku građu - Opis'),
(63, 'document', 'title', 'sr-cyrl', 'Реверс за издавање архивске грађе', 'Реверс за архивску грађу - Наслов'),
(63, 'document', 'description', 'sr-cyrl', 'Образац реверса за издавање архивске грађе.', 'Реверс за архивску грађу - Опис'),
(64, 'document', 'title', 'sr', 'Revers za izdavanje bibliotečke građe', 'Revers za bibliotečku građu - Naslov'),
(64, 'document', 'description', 'sr', 'Obrazac reversa za izdavanje bibliotečke građe.', 'Revers za bibliotečku građu - Opis'),
(64, 'document', 'title', 'sr-cyrl', 'Реверс за издавање библиотечке грађе', 'Реверс за библиотечку грађу - Наслов'),
(64, 'document', 'description', 'sr-cyrl', 'Образац реверса за издавање библиотечке грађе.', 'Реверс за библиотечку грађу - Опис'),
(65, 'document', 'title', 'sr', 'Revers za izdavanje kopija arhivske građe', 'Revers za kopije arhivske građe - Naslov'),
(65, 'document', 'description', 'sr', 'Obrazac reversa za izdavanje kopija arhivske građe.', 'Revers za kopije arhivske građe - Opis'),
(65, 'document', 'title', 'sr-cyrl', 'Реверс за издавање копија архивске грађе', 'Реверс за копије архивске грађе - Наслов'),
(65, 'document', 'description', 'sr-cyrl', 'Образац реверса за издавање копија архивске грађе.', 'Реверс за копије архивске грађе - Опис'),
(66, 'document', 'title', 'sr', 'Revers za korišćenje arhivske građe', 'Revers za korišćenje arhivske građe - Naslov'),
(66, 'document', 'description', 'sr', 'Obrazac reversa za korišćenje arhivske građe.', 'Revers za korišćenje arhivske građe - Opis'),
(66, 'document', 'title', 'sr-cyrl', 'Реверс за коришћење архивске грађе', 'Реверс за коришћење архивске грађе - Наслов'),
(66, 'document', 'description', 'sr-cyrl', 'Образац реверса за коришћење архивске грађе.', 'Реверс за коришћење архивске грађе - Опис'),
(67, 'document', 'title', 'sr', 'Revers za korišćenje bibliotečke građe', 'Revers za korišćenje bibliotečke građe - Naslov'),
(67, 'document', 'description', 'sr', 'Obrazac reversa za korišćenje bibliotečke građe.', 'Revers za korišćenje bibliotečke građe - Opis'),
(67, 'document', 'title', 'sr-cyrl', 'Реверс за коришћење библиотечке грађе', 'Реверс за коришћење библиотечке грађе - Наслов'),
(67, 'document', 'description', 'sr-cyrl', 'Образац реверса за коришћење библиотечке грађе.', 'Реверс за коришћење библиотечке грађе - Опис'),
(68, 'document', 'title', 'sr', 'Zahtev za izdavanje arhivske građe', 'Zahtev za izdavanje arhivske građe - Naslov'),
(68, 'document', 'description', 'sr', 'Obrazac zahteva za izdavanje arhivske građe.', 'Zahtev za izdavanje arhivske građe - Opis'),
(68, 'document', 'title', 'sr-cyrl', 'Захтев за издавање архивске грађе', 'Захтев за издавање архивске грађе - Наслов'),
(68, 'document', 'description', 'sr-cyrl', 'Образац захтева за издавање архивске грађе.', 'Захтев за издавање архивске грађе - Опис'),
(69, 'document', 'title', 'sr', 'Zahtev za korišćenje arhivske kartoteke', 'Zahtev za arhivsku kartoteku - Naslov'),
(69, 'document', 'description', 'sr', 'Obrazac zahteva za korišćenje arhivske kartoteke.', 'Zahtev za arhivsku kartoteku - Opis'),
(69, 'document', 'title', 'sr-cyrl', 'Захтев за коришћење архивске картотеке', 'Захтев за арх. картотеку - Наслов'),
(69, 'document', 'description', 'sr-cyrl', 'Образац захтева за коришћење архивске картотеке.', 'Захтев за арх. картотеку - Опис'),
(70, 'document', 'title', 'sr', 'Program za 2025. - IAZ', 'Program za 2025 - Naslov'),
(70, 'document', 'description', 'sr', 'Program rada institucije/arhiva za 2025. godinu.', 'Program za 2025 - Opis'),
(70, 'document', 'title', 'sr-cyrl', 'Програм за 2025. - ИАЗ', 'Програм за 2025 - Наслов'),
(70, 'document', 'description', 'sr-cyrl', 'Програм рада институције/архива за 2025. годину.', 'Програм за 2025 - Опис'),
(71, 'document', 'title', 'sr', 'Etički kodeks (ćirilični)', 'Etički kodeks - Naslov'),
(71, 'document', 'description', 'sr', 'Dokument koji definiše etičke standarde u radu.', 'Etički kodeks - Opis'),
(71, 'document', 'title', 'sr-cyrl', 'Етички кодекс', 'Етички кодекс - Наслов'),
(71, 'document', 'description', 'sr-cyrl', 'Документ који дефинише етичке стандарде у раду.', 'Етички кодекс - Опис'),
(72, 'document', 'title', 'sr', 'ED Priručnik za arhiviste', 'Priručnik za arhiviste - Naslov'),
(72, 'document', 'description', 'sr', 'Priručnik za primenu elektronskog dokumenta za arhiviste.', 'Priručnik za arhiviste - Opis'),
(72, 'document', 'title', 'sr-cyrl', 'ЕД Приручник за архивисте', 'Приручник за архивисте - Наслов'),
(72, 'document', 'description', 'sr-cyrl', 'Приручник за примену електронског документа за архивисте.', 'Приручник за архивисте - Опис'),
(73, 'document', 'title', 'sr', 'ISAAR(CPF) Standard', 'ISAAR(CPF) - Naslov'),
(73, 'document', 'description', 'sr', 'Međunarodni standard za opis nadležnosti, osoba i porodica.', 'ISAAR(CPF) - Opis'),
(73, 'document', 'title', 'sr-cyrl', 'ИСААР(ЦПФ) Стандард', 'ИСААР(ЦПФ) - Наслов'),
(73, 'document', 'description', 'sr-cyrl', 'Међународни стандард за опис надлежности, особа и породица.', 'ИСААР(ЦПФ) - Опис'),
(74, 'document', 'title', 'sr', 'ISAD(G) Standard', 'ISAD(G) - Naslov'),
(74, 'document', 'description', 'sr', 'Međunarodni standard opšteg arhivističkog opisa.', 'ISAD(G) - Opis'),
(74, 'document', 'title', 'sr-cyrl', 'ИСАД(Г) Стандард', 'ИСАД(Г) - Наслов'),
(74, 'document', 'description', 'sr-cyrl', 'Међународни стандард општег архивистичког описа.', 'ИСАД(Г) - Опис'),
(75, 'document', 'title', 'sr', 'ISDIAH Standard (srpski)', 'ISDIAH - Naslov'),
(75, 'document', 'description', 'sr', 'Međunarodni standard za opis institucija sa arhivskom građom.', 'ISDIAH - Opis'),
(75, 'document', 'title', 'sr-cyrl', 'ИСДИАХ Стандард (српски)', 'ИСДИАХ - Наслов'),
(75, 'document', 'description', 'sr-cyrl', 'Међународни стандард за опис институција са архивском грађом.', 'ИСДИАХ - Опис'),
(76, 'document', 'title', 'sr', 'Standardi ISDF', 'ISDF Standardi - Naslov'),
(76, 'document', 'description', 'sr', 'Međunarodni standard za funkcije.', 'ISDF Standardi - Opis'),
(76, 'document', 'title', 'sr-cyrl', 'Стандарди ИСДФ', 'ИСДФ Стандарди - Наслов'),
(76, 'document', 'description', 'sr-cyrl', 'Међународни стандард за функције.', 'ИСДФ Стандарди - Опис'),
(77, 'document', 'title', 'sr', 'Pravilnik o delatnosti', 'Pravilnik o delatnosti - Naslov'),
(77, 'document', 'description', 'sr', 'Interni pravilnik kojim se uređuje delatnost.', 'Pravilnik o delatnosti - Opis'),
(77, 'document', 'title', 'sr-cyrl', 'Правилник о делатности', 'Правилник о делатности - Наслов'),
(77, 'document', 'description', 'sr-cyrl', 'Интерни правилник којим се уређује делатност.', 'Правилник о делатности - Опис'),
(78, 'document', 'title', 'sr', 'Pravilnik o načinu vođenja evidencije RM', 'Pravilnik o evidenciji RM - Naslov'),
(78, 'document', 'description', 'sr', 'Pravilnik o načinu vođenja evidencije radnih mesta.', 'Pravilnik o evidenciji RM - Opis'),
(78, 'document', 'title', 'sr-cyrl', 'Правилник о начину вођења евиденције РМ', 'Правилник о евиденцији РМ - Наслов'),
(78, 'document', 'description', 'sr-cyrl', 'Правилник о начину вођења евиденције радних места.', 'Правилник о евиденцији РМ - Опис'),
(79, 'document', 'title', 'sr', 'Pravilnik o regulisanju arhivske građe', 'Pravilnik o reg. arhivske građe - Naslov'),
(79, 'document', 'description', 'sr', 'Pravilnik o regulisanju arhivske građe.', 'Pravilnik o reg. arhivske građe - Opis'),
(79, 'document', 'title', 'sr-cyrl', 'Правилник о регулацији архивске грађе', 'Правилник о рег. архивске грађе - Наслов'),
(79, 'document', 'description', 'sr-cyrl', 'Правилник о регулацији архивске грађе.', 'Правилник о рег. архивске грађе - Опис'),
(80, 'document', 'title', 'sr', 'Pravilnik o sticanju zvanja', 'Pravilnik o sticanju zvanja - Naslov'),
(80, 'document', 'description', 'sr', 'Pravilnik kojim se uređuje postupak sticanja stručnih zvanja.', 'Pravilnik o sticanju zvanja - Opis'),
(80, 'document', 'title', 'sr-cyrl', 'Правилник о стицању звања', 'Правилник о стицању звања - Наслов'),
(80, 'document', 'description', 'sr-cyrl', 'Правилник којим се уређује поступак стицања стручних звања.', 'Правилник о стицању звања - Опис'),
(81, 'document', 'title', 'sr', 'Program poslovanja Centra Most za 2025.', 'Program poslovanja Most 2025 - Naslov'),
(81, 'document', 'description', 'sr', 'Program poslovanja Centra Most za 2025. godinu.', 'Program poslovanja Most 2025 - Opis'),
(81, 'document', 'title', 'sr-cyrl', 'Програм пословања Центра Мост за 2025.', 'Програм пословања Мост 2025 - Наслов'),
(81, 'document', 'description', 'sr-cyrl', 'Програм пословања Центра Мост за 2025. годину.', 'Програм пословања Мост 2025 - Опис'),
(82, 'document', 'title', 'sr', 'Teritorija Arhiva', 'Teritorija Arhiva - Naslov'),
(82, 'document', 'description', 'sr', 'Dokument koji definiše teritoriju nadležnosti Arhiva.', 'Teritorija Arhiva - Opis'),
(82, 'document', 'title', 'sr-cyrl', 'Територија Архива', 'Територија Архива - Наслов'),
(82, 'document', 'description', 'sr-cyrl', 'Документ који дефинише територију надлежности Архива.', 'Територија Архива - Опис'),
(83, 'document', 'title', 'sr', 'Zakon o kulturnim dobrima (KD)', 'Zakon o KD - Naslov'),
(83, 'document', 'description', 'sr', 'Tekst Zakona o kulturnim dobrima.', 'Zakon o KD - Opis'),
(83, 'document', 'title', 'sr-cyrl', 'Закон о културним добрима (КД)', 'Закон о КД - Наслов'),
(83, 'document', 'description', 'sr-cyrl', 'Текст Закона о културним добрима.', 'Закон о КД - Опис');
