<section class="py-16 md:py-24 bg-background"><div class="container mx-auto px-6"><div class="text-center mb-12 md:mb-16"><h2 class="text-3xl md:text-5xl font-bold mb-4 glow decorative-line text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_1e2371_709803']['text'] ?? 'Naša Istorija', ENT_QUOTES, 'UTF-8'); ?></h2><p class="text-base md:text-xl text-secondary_text max-w-3xl mx-auto"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_a0945c_9fb44b']['text'] ?? 'Više od jednog veka čuvanja
                    kulturnog nasleđa', ENT_QUOTES, 'UTF-8'); ?></p></div><div class="relative max-w-5xl mx-auto"><div class="timeline-glow absolute left-4 md:left-8 top-0 bottom-0"></div><div class="space-y-8 md:space-y-12"><div class="relative pl-16 md:pl-24 group"><div class="absolute left-0 w-12 h-12 md:w-16 md:h-16 bg-primary rounded-full flex items-center justify-center shadow-lg shadow-primary/30 group-hover:scale-110 transition"><span class="text-lg md:text-xl font-bold text-white">1912</span></div><div class="glass-dark rounded-2xl p-6 md:p-8 hover:bg-secondary_background/30 transition"><h3 class="text-xl md:text-3xl font-bold mb-3 text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_af4857_62a549']['text'] ?? 'Osnivanje Arhiva', ENT_QUOTES, 'UTF-8'); ?></h3><p class="text-secondary_text text-base md:text-lg"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_a8b889_f9585b']['text'] ?? 'Istorijski arhiv osnovan kao deo
                                gradskog muzeja.
                                Početna
                                kolekcija obuhvata 800 dokumenata iz lokalne istorije i administrative.', ENT_QUOTES, 'UTF-8'); ?></p></div></div><div class="relative pl-16 md:pl-24 group"><div class="absolute left-0 w-12 h-12 md:w-16 md:h-16 bg-primary rounded-full flex items-center justify-center shadow-lg shadow-primary/30 group-hover:scale-110 transition"><span class="text-lg md:text-xl font-bold text-white">1945</span></div><div class="glass-dark rounded-2xl p-6 md:p-8 hover:bg-secondary_background/30 transition"><h3 class="text-xl md:text-3xl font-bold mb-3 text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_fc2213_3c14f4']['text'] ?? 'Posleratna Obnova', ENT_QUOTES, 'UTF-8'); ?></h3><p class="text-secondary_text text-base md:text-lg"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_3bfdfe_c38fe2']['text'] ?? 'Premeštanje u novi prostor i
                                započinjanje sistematske
                                organizacije ratom oštećene građe. Inkorporacija arhiva likvidiranih institucija.', ENT_QUOTES, 'UTF-8'); ?></p></div></div><div class="relative pl-16 md:pl-24 group"><div class="absolute left-0 w-12 h-12 md:w-16 md:h-16 bg-primary rounded-full flex items-center justify-center shadow-lg shadow-primary/30 group-hover:scale-110 transition"><span class="text-lg md:text-xl font-bold text-white">1987</span></div><div class="glass-dark rounded-2xl p-6 md:p-8 hover:bg-secondary_background/30 transition"><h3 class="text-xl md:text-3xl font-bold mb-3 text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_6fef7f_a7d936']['text'] ?? 'Nova Zgrada', ENT_QUOTES, 'UTF-8'); ?></h3><p class="text-secondary_text text-base md:text-lg"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_8b6e79_cf4751']['text'] ?? 'Preseljenje u posebno projektovanu
                                zgradu sa modernim
                                depovima, klimatizacijom i prostorima za čuvanje arhivske građe.', ENT_QUOTES, 'UTF-8'); ?></p></div></div><div class="relative pl-16 md:pl-24 group"><div class="absolute left-0 w-12 h-12 md:w-16 md:h-16 bg-primary rounded-full flex items-center justify-center shadow-lg shadow-primary/30 group-hover:scale-110 transition"><span class="text-lg md:text-xl font-bold text-white">2015</span></div><div class="glass-dark rounded-2xl p-6 md:p-8 hover:bg-secondary_background/30 transition"><h3 class="text-xl md:text-3xl font-bold mb-3 text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_0ac697_934f5f']['text'] ?? 'Digitalna Transformacija', ENT_QUOTES, 'UTF-8'); ?></h3><p class="text-secondary_text text-base md:text-lg"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_0b657c_4387b2']['text'] ?? 'Započinjanje masovnog projekta
                                digitalizacije.
                                Lansiranje
                                online platforme sa pretražljivom bazom podataka i digitalnom čitaonicom.', ENT_QUOTES, 'UTF-8'); ?></p></div></div><div class="relative pl-16 md:pl-24 group"><div class="absolute left-0 w-12 h-12 md:w-16 md:h-16 bg-primary rounded-full flex items-center justify-center shadow-lg shadow-primary/30 group-hover:scale-110 transition pulse"><span class="text-lg md:text-xl font-bold text-white">2023</span></div><div class="glass-dark rounded-2xl p-6 md:p-8 hover:bg-secondary_background/30 transition border-2 border-primary"><h3 class="text-xl md:text-3xl font-bold mb-3 text-primary_text"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_8dfc84_af840a']['text'] ?? 'AI i Inovacije', ENT_QUOTES, 'UTF-8'); ?></h3><p class="text-secondary_text text-base md:text-lg"><?= htmlspecialchars($dynamicText['t_istorijskiarhiv_90c920_724c53']['text'] ?? 'Implementacija veštačke inteligencije za
                                automatsku
                                kategorizaciju, OCR prepoznavanje rukopisa i naprednu semantičku pretragu.', ENT_QUOTES, 'UTF-8'); ?></p></div></div></div></div></div></section>